### ISSUE TITLE
There are 0 reads

### ISSUE THREAD

**Issue by AndreaAguadoM** [cbg-ethz/PredictHaplo#25]
Hello

I downloaded this tool from bioconda, but when trying to use it over my sample, the following error appears: 

prefix = AND19006
  cons = reference.fasta
  visualization_level = 1
  FASTAreads = AND19006.sam
  have_true_haplotypes = 0
  FASTAhaplos = 
  do_local_Analysis = 1
After parsing the reads in file AND19006.sam: average read length= -nan 0
First read considered in the analysis starts at position 100000. Last read ends at position 0
There are 0 reads
Segmentation fault (core dumped)

This is the command line that I wrote so PredictHaplo could be executed: 

predicthaplo --sam AND19006.sam --reference reference.fasta --prefix AND19006 --have_true_haplotypes 0

Is there someone who can help me? 
Thanks in advance!

**Comment by kpj** [comment]
The bioconda version and the master branch of this repository are quite out-of-sync.
Could you rerun your analysis with the latest version (from this repository) and check if the error disappears?

**Comment by AndreaAguadoM** [comment]
Yes! it has dessapeared, thank you!
